[32m2025-05-02 20:17:38 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 706bbedf-2048-4d70-8646-4f29fc0bd54b - 88626 - LOGS_CAPTURED - Started capturing logs in process (pid: 88626).
[32m2025-05-02 20:17:38 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 706bbedf-2048-4d70-8646-4f29fc0bd54b - 88626 - taxi_trips_file - STEP_START - Started execution of step "taxi_trips_file".
[32m2025-05-02 20:17:38 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 706bbedf-2048-4d70-8646-4f29fc0bd54b - 88626 - taxi_trips_file - STEP_FAILURE - Execution of step "taxi_trips_file" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips_file"::

NameError: name 'constants' is not defined

Stack Trace:
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 401, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/project-dagster-university/dagster_university/dagster_essentials/dagster_essentials/assets/trips.py", line 15, in taxi_trips_file
    with open(constants.TAXI_TRIPS_TEMPLATE_FILE_PATH.format(month_to_fetch), "wb") as output_file:
              ^^^^^^^^^
[0m
