[32m2025-05-05 15:58:08 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 19d79903-f038-421f-bb56-acc410eee40d - 84561 - LOGS_CAPTURED - Started capturing logs in process (pid: 84561).
[32m2025-05-05 15:58:08 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 19d79903-f038-421f-bb56-acc410eee40d - 84561 - taxi_zones - STEP_START - Started execution of step "taxi_zones".
[32m2025-05-05 15:59:51 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 19d79903-f038-421f-bb56-acc410eee40d - 84561 - taxi_zones - STEP_FAILURE - Execution of step "taxi_zones" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_zones"::

duckdb.duckdb.IOException: IO Error: Could not set lock on file "/workspaces/project-dagster-university/dagster_university/dagster_essentials/data/staging/data.duckdb": Conflicting lock is held in /usr/local/bin/python3.11 (PID 40309). See also https://duckdb.org/docs/connect/concurrency

Stack Trace:
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 401, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/project-dagster-university/dagster_university/dagster_essentials/dagster_essentials/assets/trips.py", line 85, in taxi_zones
    conn = backoff(
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/backoff.py", line 71, in backoff
    raise to_raise
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/backoff.py", line 65, in backoff
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
[0m
